### ISSUE TITLE
[Question] Anyone has access to everything?

### ISSUE THREAD

**Issue by tideodk** [PhlexPlexico/G5V#142]
Hi! :-)
Thank you for your awesome work. I finally got it up and running.

I was curious to see how your webpanel actually worked.

As far as I am aware, everyone that signs up has access to create seasons and matches. There's no way to time matches (Lets say, create a match that first starts at 8). I dont see anywhere where that would be a possibility. Could you let me know if there is?

**Comment by PhlexPlexico** [comment]
Thanks and hey!

That is correct, anyone can sign up and create matches, however they will need to provide their own servers and team (provided there aren't any that are public).

Right now, there is no possibility of auto-creating matches and whatnot, because that would require a bit more work with event listeners and timers, and I haven't really had the time to look into it. Pull requests are always welcome, as that would be all on the API side! It's always possible, just yet to be implemented is all. I'm currently working on fixing some bugs in get5 itself here (mainly backup/restore issues), and I have some [features](https://github.com/users/PhlexPlexico/projects/1) I'd like to get out in this tech stack before looking into it, but anyone should be able to start digging into it if they so choose :)

Thanks!

**Comment by tideodk** [comment]
> Thanks and hey!
> 
> That is correct, anyone can sign up and create matches, however they will need to provide their own servers and team (provided there aren't any that are public).
> 
> Right now, there is no possibility of auto-creating matches and whatnot, because that would require a bit more work with event listeners and timers, and I haven't really had the time to look into it. Pull requests are always welcome, as that would be all on the API side! It's always possible, just yet to be implemented is all. I'm currently working on fixing some bugs in get5 itself here (mainly backup/restore issues), and I have some [features](https://github.com/users/PhlexPlexico/projects/1) I'd like to get out in this tech stack before looking into it, but anyone should be able to start digging into it if they so choose :)
> 
> Thanks!

I noticed, especially the feature that "players" that login can even create matches. But I'm sure that adding "hiding" of the menus for non-admin users can't seem to be that hard.
Thanks for your work! :-) I hope to see it grow more. I haven't yet found something that works like yours, and I hope to see some of the features I require implemented at some point.

**Comment by PhlexPlexico** [comment]
I think if you look around the forks of this project, I think someone had implemented what you were asking, however there is also functionality that players get when logging in (easy connect button like faceit, as an example). 

The aim for this was to just make match management for tournament admins easier, as well as some more defined stats, so having users log in has never been an issue. If they'd like to set up their own servers to play on with their own teams, it should be more than okay to do that imo :)

But thanks, I'm glad it is fitting your needs!
