### ISSUE TITLE
[Request] Match Import from Challonge

### ISSUE THREAD

**Issue by Iwhite67** [PhlexPlexico/G5V#145]
Hello

This is a feature request to have possibility import match from Challonge

In continuity of challonge integration, actually, he missing match import

**Comment by PhlexPlexico** [comment]
This is intentional, as there is no way to actually create teams with Steam auths attached to them. It is still up to the TO to assign steam IDs within the teams before a match can be created. Teams must have steam IDs within them when the match is created, or else the match config will be empty and no one will be able to join the game. As of right now, Challonge has no way of importing raw text fields from their API, so it fails to meet that requirement, so we cannot create matches from it.

**Comment by Iwhite67** [comment]
so, this is possible to have more info on G5API, i check the API to see what body and Header i need to put for create a match

**Comment by PhlexPlexico** [comment]
I'm not sure I follow. The issue isn't with G5API, but the Challonge API not being able to have any identifiers. There is currently a lab test to allow free-formed text on their front-end, but that is not exposed to the API at all, so there's no way to grab multiple Steam IDs.

As for POSTing matches, you just need a header with your `user-api` where the value is `<user_id>:<api_key>`. If you wish to POST a match, you can view the API docs [here](https://phlex.avidgamers.me/api/api-docs/#/matches/post_matches) :)
