### ISSUE TITLE
[BUG] Servers are not getting added

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/G5V#25]
@PhlexPlexico getting error while adding the server. Also not able to check server status. Both seems to be working on your http://phlex.avidgamers.me:8080/

![Screenshot 2020-11-02 at 12 45 02 PM](https://user-images.githubusercontent.com/39219862/97840232-aaa84e00-1d09-11eb-9bff-522c92cea4d3.png)

**Comment by PhlexPlexico** [comment]
This is more to do with G5API not being able to query the server once it's been added, most likely due to an issue with `rcon-srcds`. Please do a git pull (on G5API) so you're on the latest version, then call `yarn` in that directory. It should update to a patched version of that package, and you should be able to add servers. Let me know if that works!

Thanks!

**Comment by xe1os** [comment]
@PhlexPlexico Thanks it worked !! :)

**Comment by PhlexPlexico** [comment]
I've changed implementations as well... There may be some unintended side effects, but we'll see how well it works!
