### ISSUE TITLE
[Request] Toornament Integration

### ISSUE THREAD

**Issue by trashcluster** [PhlexPlexico/G5V#28]
Would be extra nice to have Toornament integration into the panel with auto match creation ans score reporting as well as team locking and all, would greatly enhance the tournaments admins QoL :) Would love to contribute to the project in a way but i never touched Vue or JavaScript for that matter so would need some help !

**Comment by PhlexPlexico** [comment]
Hey trashcluster!

From what I understand, Toornament seems to be something that is a platform that _kind of_ trades punches with this software. At the cost of server creation, and automated matches through get5/server calls through the panel, you get some additional information from the players/manage their teams, and seeding for matches to setup?

I think, personally, G5API is something that is meant to be used independently of other platforms/integrations since it can take care of tournaments, seasons, and players/teams. The API can also allow creation of teams/matches/etc through other means, like a Discord Bot (like PUGs, proof-of-concept [here](https://github.com/PhlexPlexico/G5-Bot/tree/api)). There's also a few things I would like to avoid, such as branding, that I wouldn't be able to do with what Toornament requests to have (after some chats with Toornament I've had in prior [projects](https://github.com/PhlexPlexico/get5-web/issues/50) thoughts to implementing).

If you're managing a tournament and would like to use G5API and G5V, I would recommend setting up a private instance with organizers as Super Administrators. This would allow people to manage teams, create matches with any team, use any server available on that instance, and allow creation of tournaments/seasons with leaderboards included for teams and players within that tournament/season as well.

However, I'm not exactly opposed to integrating! This is just something that has always been lower priority, and in contest to the Challonge API as well.

From what I see, you would like something akin to a "Toornament Section" within the front-end, that will:

- Import "Registrations" (in this case, let's call them teams.)
- Import "Tournaments" (so this will match up with the `start_date`, `end_date` and `title` of a Season in the API)
- Import "Matches" (this would be the hard one, as we need to now link `team_id` to the `registration`, this may require changes on G5API as well).
- Assign a server to a Match (once a match is imported, we can set `ignore_server` to `true`, and allow updating of matches after the fact. This is done in the aforementioned PUG bot).

I could see the first two being relatively simple to implement, and would only need to done on the front end. The next would require a bit more effort on G5API, as it requires a way to link data back from Toornament, to the API itself (perhaps creating a new table like `toornament_team_link` which links teh toornament registration ID to the team_id).

This also doesn't take care of the fact of post match, which would require some more thought into how the `get5-apistats` plugin interacts with HTTP calls. But I think that would be another discussion in of itself :)

Thanks!

**Comment by PhlexPlexico** [comment]
Hey! So it's been about a year here and I was taking a peep at the API for Toornament, but it appears that in order to use the API you'd have to pay a license of 400 EUR/month/project. I'm now unsure if this is something that we should continue looking into or not now, since that seems to be a pretty steep price tag.

**Comment by trashcluster** [comment]
Yeah right, they recently switched to paid plans for their API access which makes their tool much less useful than before.

It was fun while it lasted i guess
