### ISSUE TITLE
Wingman

### ISSUE THREAD

**Issue by YungGhost1377** [PhlexPlexico/G5V#29]
Is it possible to make a wingman mode?

**Comment by PhlexPlexico** [comment]
Hi!

I'm not exactly sure what you mean. This panel is more for competitive 5v5 tournaments. It is possible to work around this though, and adjust your get5 config (`live.cfg`) on your server as well. The only changes you would need to make code-wise would be the list of maps that you wish to select, which are located here: https://github.com/PhlexPlexico/G5V/blob/3df33476bda4b1054956404d5a6217bbd73f96bb/src/components/NewMatchForm.vue#L117

You can adjust those values to be anything you wish, instead of `de_dust2` for example, you could change the values to `de_shortdust`. Then, set Players Per Team to 2. 

The map list could be something I change in the future as well, and make it more modular (have it be in a settings file maybe?).

**Comment by YungGhost1377** [comment]
And in the game, the veto will be transmitted from the api?

sry my eng is very bad, I'm from Russia :)

**Comment by PhlexPlexico** [comment]
Yup! The API sends over the maplist to veto in-game, and so long as the maps exist on the server, it should have no problem changing maps once the veto is complete.

And no worries, I know zero Russian so you're already many steps ahead of me :)

**Comment by YungGhost1377** [comment]
thanks a lot, I'll try this option
