### ISSUE TITLE
[BUG]Error login steam 

### ISSUE THREAD

**Issue by furzich2015** [PhlexPlexico/G5V#44]
Hello. After I wanted to start it again after a short break to check the discord bot, I got an error when logging into Steam.
![image](https://user-images.githubusercontent.com/36245898/106685900-0668c880-65d2-11eb-9968-0fc07541f0d3.png)
ERROR:
![image](https://user-images.githubusercontent.com/36245898/106685920-0ec10380-65d2-11eb-9bc6-79956a788577.png)
![image](https://user-images.githubusercontent.com/36245898/106686291-ba6a5380-65d2-11eb-954c-0033aca8138c.png)
![image](https://user-images.githubusercontent.com/36245898/106686259-af172800-65d2-11eb-9f05-36e44b1ffeca.png)
Configs: 
![image](https://user-images.githubusercontent.com/36245898/106686160-90189600-65d2-11eb-80e2-9419fc0d2d18.png)
![image](https://user-images.githubusercontent.com/36245898/106686179-960e7700-65d2-11eb-88ea-3f73b0190675.png)

**Comment by PhlexPlexico** [comment]
Hi!

This problem is rather unfortunate since I was running into this issue as well sometime ago (seen here: https://github.com/PhlexPlexico/G5API/issues/11). I luckily had the opportunity to change machines and it seems it was working fine for me. However, looking in passport-steam's repository, I can see that this may be an issue with time on your system. 

See the comment from someone having the issue you're facing here: https://github.com/liamcurry/passport-steam/issues/68#issuecomment-658367752

**Comment by furzich2015** [comment]
Ohh, okay, i try fix it

**Comment by furzich2015** [comment]
Yeah, i fix it ^^
Need install NTP (if not installed)
**sudo apt install ntp**
and settings pool
sudo nano /etc/ntp.conf:
**_server 0.europe.pool.ntp.org
server 1.europe.pool.ntp.org
server 2.europe.pool.ntp.org
server 3.europe.pool.ntp.org_**

**Comment by PhlexPlexico** [comment]
Awesome to hear! Glad it was fixed.
