### ISSUE TITLE
[Request] Display Frontend for Normal Users and backend for Admins for all Options

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/G5V#5]
We can have different Frontend after the Users Log in. 

Normal User - Profile Details with Brief of Stats like Kills , Deaths and Charts 
1) Show My Matches
2) Show My Stats
3) Show Upcoming Matches

Admin User - (We can use other URL also like /admin or change it as per requirements)
All functions related to Matches , Teams and Servers and Seasons.

**Comment by PhlexPlexico** [comment]
Instead of writing completely different routes, I plan on re-using routes that present the data differently. If you would like to see an example, please look at the `/teams/:team_id` route. The new/edit team members, delete buttons, etc, are all still within the same route, just loaded depending on who is loading them. 

I'll see what I can do once I have the basics put in for this, though 👍

**Comment by PhlexPlexico** [comment]
Yeah, I'm more down for having things integrating then recreating routes when you can just use `v-if` and conditional rendering to let the admins do their things. This can be observed on the match pages, or even in the Team views. If it's alright with you, I think I'm going to close this request.
