### ISSUE TITLE
[BUG] Listing my teams doesn't work fine.

### ISSUE THREAD

**Issue by Pablo-Barros** [PhlexPlexico/G5V#51]

**Comment by PhlexPlexico** [comment]
Was talking over Twitter for this issue. It turns out that when a user creates a team, it does not show on their "My Teams" route even if they own the team. This is caused by the following:

https://github.com/PhlexPlexico/G5V/blob/4df9086c0c7baf7884d8530d4cf0e65bbce0e382/src/components/TeamsTable.vue#L76-L78

A simple fix is to check if the team owner is the same as the logged in user, which I conveniently forgot to check.

**Comment by PhlexPlexico** [comment]
Fixed!
