### ISSUE TITLE
[Visual BUG/FR] "Successfully added player (steamid) to team team1" add team name instead

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5V#86]
![image](https://user-images.githubusercontent.com/26146502/140653457-8a6c7a90-7cd0-4572-b387-4069410d5b82.png)
Can this display the team name instead? Just to be sure that someone less skilled doesn't miss what team that player is supposed to be added to.

**Comment by PhlexPlexico** [comment]
I'm setting this as a won't fix because I believe (from searching around repoes, etc), that message is brought back from the game server.

Front end calls `adduser` to API -> API uses an rcon command `get5_add_user` or similar to game server -> game server replied with response indicating success or failure -> API either reports error with a custom message, or the reply from RCON.

Also, considering during setup for matches it asks who is Team 1 and who is Team 2, I figured it would be pretty explanatory from therein that Team 1 = the first team selected and Team 2 is the second. This is something I can't fix since the response (I believe) is directly from get5, not any of the stuff I've made.
