### ISSUE TITLE
API URL 404 Not Found

### ISSUE THREAD

**Issue by shaikhnedab** [PhlexPlexico/G5V#96]
I am trying to host this panel using apache2 web server.
Tried everything but cant get API URL to work.
Getting below error
![image](https://user-images.githubusercontent.com/55206494/148650268-ca237c90-0113-4fce-a785-57b615dd9a38.png)

here is API production config.
```
{
  "server": {
    "port": 3301,
    "hostname": "http://match.kebabnation.xyz",
    "dbKey": "redacted",
    "steamAPIKey": "redacted",
    "sharedSecret": "redacted",
    "clientHome": "http://match.kebabnation.xyz",
    "useRedis": true,
    "apiURL": "http://match.kebabnation.xyz/api/",
    "uploadDemos": false
  },
```

here is vue config
```
module.exports = {
  transpileDependencies: ["vuetify"],
  devServer: {
    public: "match.kebabnation.xyz:80",
    proxy: {
      "^/api": {
        target: "http://kebabnation.xyz:3301",
        changeOrigin: true,
        pathRewrite: {
          "^/api": ""
        }
      }
    }
  }
};
```
Apache2 config.
```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName match.kebabnation.xyz
    DocumentRoot /var/www/G5V/dist
</VirtualHost>
```

**Comment by PhlexPlexico** [comment]
If you're using apache2 that means you'll have to setup a reverse proxy. 

I don't believe you need the `/` at the end of the `apiURL` so maybe remove that.

You'll most likely have to search up "Apache2 reverse proxy" for a specific url. I think it may be something like this within your `VirtualHost` tag?

```
ProxyPass /api  http://match.kebabnation.xyz
ProxyPassReverse /api http://match.kebabnation.xyz
```

Just make sure those directives are enabled as well. There may be some regex you'll have to do if someone provides a value like `/API/test` or something, but I'm not sure since I've never set this up with apache2/tomcat.

**Comment by shaikhnedab** [comment]
well it worked.
thank you very much.
last question is how do I set ``NODE_ENV`` to production. Right now when   I run ``yarn startprod`` throw error like 
``No NODE_ENV set. Please set NODE_ENV or else default is DEVELOPMENT.``

**Comment by shaikhnedab** [comment]
migrated to nginx and everything is working as expected. thanks for your time
