### ISSUE TITLE
Make Team TAG optional

### ISSUE THREAD

**Issue by stranden** [PhlexPlexico/G5V#97]
Hi Phlex,

I have a request regarding getting the Team TAG optional.
Mostly because it is optional in the match config which are send to the server.

I'm not sure if it a G5V issue or more a G5API issue.

See attached image regarding the TAG
![image](https://user-images.githubusercontent.com/18518722/150125123-ad247d79-8c92-4e81-8e5f-f7d8a26e4b8d.png)

It is mostly because I don't know the TAG of the enemy teams, and just wanted to use the builtin team tag in CSGO instead.

Best regards

**Comment by PhlexPlexico** [comment]
Heya!

So, the tag is optional in the database, but this front-end is supposed to be used more for a tournament management type of use, which means that a team tag would have to be put in there, as to avoid people changing groups in-game to have their tags change. I'm not exactly sure I've ever ran into a part where I wouldn't know what a tag was. If I was unsure, I would just put the team name as the tag as well, I hesitate letting that be null because I myself have been known to go across a few fields too quickly when trying to create teams.

**Comment by stranden** [comment]
Hi,

Okay so just to be sure, if I insert the team via the API (api/teams/) I should be able to do it without the tag?
Because that is actually what I'm doing.

I pull the teams from another site and inserting them directly in the database via G5API.
I'm only using the G5V for creating the matches right now, and to have something visual to get a quick overview.

**Comment by PhlexPlexico** [comment]
Yup! You should be able to keep the tag as null, and it won't insert it into the API at all, the database itself allows null values :)

Thanks!

**Comment by stranden** [comment]
Thanks for the clarification - I will just close this issue then! 👍
